# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/puertask/Documents/atan_phase_detector_x5/atan_phase_detector_x5.srcs/sources_1/ip/mult_32_16/mult_32_16.xci
# IP: The module: 'mult_32_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/puertask/Documents/atan_phase_detector_x5/atan_phase_detector_x5.srcs/sources_1/ip/mult_32_16/mult_32_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_32_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/puertask/Documents/atan_phase_detector_x5/atan_phase_detector_x5.srcs/sources_1/ip/mult_32_16/mult_32_16.xci
# IP: The module: 'mult_32_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/puertask/Documents/atan_phase_detector_x5/atan_phase_detector_x5.srcs/sources_1/ip/mult_32_16/mult_32_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_32_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
