# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tffg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/puertask/Documents/local_oscillator/local_oscillator.cache/wt [current_project]
set_property parent.project_path C:/Users/puertask/Documents/local_oscillator/local_oscillator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/imports/Source/prngen.v
  C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/imports/Source/loLookup.v
  C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/new/loChan.v
  C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/imports/Source/phaseGen.v
  C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/imports/Source/lo.v
}
read_edif C:/Users/puertask/Documents/local_oscillator/local_oscillator.srcs/sources_1/imports/Source/loLookup.ngc
synth_design -top lo -part xc7k160tffg676-2
write_checkpoint -noxdef lo.dcp
catch { report_utilization -file lo_utilization_synth.rpt -pb lo_utilization_synth.pb }
